### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by xogeny** [basarat/ts-npm-module#1]
What is unclear to me is how you would go about doing testing here.  I'm thinking of something that could be done with an `npm test` command.

I'm specifically thinking of `mocha` and keeping tests in a distinct tree.  It isn't clear to me how you refer to the files within the module in a way that Node will be happy with.  Perhaps that's a bigger issue related to Typescript + npm + mocha.

**Comment by basarat** [comment]
`ts/tests` ?

**Comment by xogeny** [comment]
OK, I don't think I was very clear on what the issues were here.  I figured most of this out on my own and it might be useful to others.  When I get some time, I'll fork this and send you a pull request and you can decide whether you think there is value in incorporating it.

**Comment by basarat** [comment]
Cheers :rose:
