### ISSUE TITLE
support ES6 module consumption?

### ISSUE THREAD

**Issue by jamesmanning** [basarat/ts-npm-module#3]
If the module consumer is attempting to use the module with --module=es6 then the compiler (tried ntsc, tsc 1.7.5, and tsc nightly) fails to find the module.

The minimal repro I could come up with is just changing target and module to es6 in the tsconfig.json like https://github.com/jamesmanning/ts-npm-module-consume/commit/70706e3280c2ce4cca04f7f8accbc22b5ba5284c

With that change, the compile fails with:

```
index.ts(2,23): error TS2307: Cannot find module 'ts-npm-module'.
```

My scenario is attempting to use such a module from webpack using babel and ts-loader - the repro for that is https://github.com/jamesmanning/webpack-react-typescript-demo/commit/519fb9013065a3125742be804b20703e42d747bb which shows the same issue (since the tsconfig.json uses module=es6)

![image](https://cloud.githubusercontent.com/assets/225626/12223955/3e8f8258-b7b3-11e5-9446-f37398b65e70.png)

Worth noting that atom-typescript still works fine, including F6 build, but since ts-loader can't use it (presumably because the compiler can't), then I can't use it in this kind of webpack configuration AFAICT?

Thanks!

**Comment by basarat** [comment]
One needs to use `moduleResolution` `node` as mentioned here : https://github.com/jamesmanning/ts-npm-module-consume/commit/70706e3280c2ce4cca04f7f8accbc22b5ba5284c :rose:

**Comment by jamesmanning** [comment]
Thank you @basarat !!

**Comment by basarat** [comment]
@jamesmanning all those thank yous' in all those forums ... _thank you!_ :rose:
